# Generated by Django 2.2.5 on 2019-09-08 08:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('mail', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(6)])),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
    ]
