# Generated by Django 2.2.5 on 2019-09-08 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190908_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='exam',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='api.Exam'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Content'),
        ),
    ]
