# Generated by Django 2.2.5 on 2019-09-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190908_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='bef_comment',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='aft_comments', to='api.Comment'),
            preserve_default=False,
        ),
    ]
