# Generated by Django 2.2.5 on 2019-09-08 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_bef_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bef_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aft_comments', to='api.Comment'),
        ),
    ]
