# Generated by Django 2.2.5 on 2019-09-08 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190908_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='receiver',
        ),
    ]
