# Generated by Django 2.2.5 on 2019-09-08 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_comment_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bef_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aft_comments', to='api.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.Exam'),
        ),
    ]
