# Generated by Django 2.2.5 on 2019-09-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_content_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.User'),
        ),
    ]
